#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF
CREATE SCHEMA IF NOT EXISTS agents AUTHORIZATION "$POSTGRES_USER";
GRANT USAGE, CREATE ON SCHEMA agents TO "$POSTGRES_USER";
EOF
