http:
  routers:
    agents-telegram-webhook-local:
      entryPoints:
        - web
      middlewares:
        - agents-security
      priority: 100
      rule: Host(`mastra.localhost`) && PathPrefix(`/telegram/webhook/`)
      service: agents

    agents-local:
      entryPoints:
        - web
      middlewares:
        - agents-auth
        - agents-security
      priority: 10
      rule: Host(`mastra.localhost`)
      service: agents

    agents-telegram-webhook-prod:
      entryPoints:
        - web
        - websecure
      middlewares:
        - agents-security
      priority: 100
      rule: Host(`api.limateixeira.com.br`) && PathPrefix(`/telegram/webhook/`)
      service: agents
      tls:
        certResolver: letsencrypt

    agents-prod:
      entryPoints:
        - web
        - websecure
      middlewares:
        - agents-auth
        - agents-security
      priority: 10
      rule: Host(`api.limateixeira.com.br`)
      service: agents
      tls:
        certResolver: letsencrypt

  services:
    agents:
      loadBalancer:
        servers:
          - url: http://agents:4111

  middlewares:
    agents-security:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: no-referrer
    agents-auth:
      basicAuth:
        usersFile: /run/secrets/traefik_users
